### PR TITLE
Fixing bugs with setting up custom SSH port

### PR DESCRIPTION
**Pull request by ArseniiPetrovich**
Previously if somebody changed port to custom using `custom_ssh_port` and then back to default - firewall rules were not set accordingly and VM become locked

### CODE REVIEW

**Comment by phahulin** [comment]
If I set `custom_ssh_port` the following error comes out:
```
TASK [authority-preconf : Save old SSH port to variable] **************************************************************************************************************************************************************************************
fatal: [137.117.33.29]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible_port' is undefined\n\nThe error appears to have been in '/home/xaxa/Work/ramdisk/test/deployment-bridge/upgradable-wo-parity/roles/authority-preconf/tasks/sshd.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Save old SSH port to variable\n  ^ here\n"}
```
I guess it's because `ansible_port` is not set to `22` by ansible if not set by user explicitly https://github.com/ArseniiPetrovich/deployment-bridge/blob/2596e8ee65facb0ef47fe6d7f07df3cb2fb19e0b/upgradable-wo-parity/roles/authority-preconf/tasks/sshd.yml#L3

**Comment by phahulin** [comment]
Also, "Doublecheck if computer..." step should go _before_ changing sshd config. Otherwise, if port is not open, user will lose access to the server.

**Comment by phahulin** [comment]
Oh, I see, it's impossible, is it? If nothing is listening on the other side, then there is no way to tell

**Comment by ArseniiPetrovich** [comment]
As for "undefined variable" error - I've upload a fix, that is going to correct it. It adds default value for cases when `ansible port` does not explicitly set.
What's considering port listening - yes. Changing of SSH port, actually, kind of risky thing - we can't tell if everything is going right before we actually switch the port. All we can do is to check everything before starting modification. I mean, it will work best of all if we will leave this play as an optional one, for users, who wants best security and have a clear VM with no other tools installed that can broke connection to server while they execute this play.

**Pull request merged**
